remote_theme: jekyll/minima
minima:
  skin: solarized-dark
  social_links:
    - { platform: github,  user_url: "https://github.com/lucianoayres" }
    - { platform: linkedin, user_url: "https://linkedin.com/in/lucianoayres" }
title: Luciano Ayres' Blog
author: Luciano Ayres
description: Personal Blog
