remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: linkedin, user_url: "https://linkedin.com/in/lucianoayres" }
    - { platform: github,  user_url: "https://github.com/lucianoayres" }
title: Luciano Ayres' Blog
author: 
  name: Luciano Ayres
description: A blog where ideas branch out and merge.
show_excerpts: true
